---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: moldavite
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/thoth-station/moldavite-api:v0.0.1
      importPolicy: {}
      referencePolicy:
        type: Local
